apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.name }}
    type: api
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: api-vimalmenon
  strategy: {}
  template:
    metadata:
      labels:
        app: api-vimalmenon
        type: api
    spec:
      containers:
        - image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
          name: {{ .Values.deployment.name}}-pod

