name: Check Code Quality

on:
  push:
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Run Tox
      run: |
        poetry run tox

